language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip -q install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  # - py.test -v --cov=dtables dtables
  - ./unittest.sh
  - coveralls