# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 21:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 8, 21, 39, 34, 905692)),
            preserve_default=False,
        ),
    ]
